CREATE USER MATVEY IDENTIFIED BY MATVEY DEFAULT TABLESPACE COOL_GOLD_DISK QUOTA UNLIMITED ON COOL_GOLD_DISK;
GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE VIEW,
    CREATE SEQUENCE,
    DELETE ANY TABLE,
    DROP ANY TABLE,
    DROP ANY PROCEDURE,
    DROP ANY TRIGGER,
    DROP ANY VIEW,
    ALTER ANY TABLE,
    ALTER ANY PROCEDURE,
    ALTER ANY TRIGGER TO MATVEY;