SELECT ALL_TAB_COLUMNS.COLUMN_ID ,ALL_TAB_COLUMNS.COLUMN_NAME,
       ALL_TAB_COLUMNS.DATA_TYPE,
       ALL_COL_COMMENTS.COMMENTS
FROM ALL_TAB_COLUMNS
         INNER JOIN ALL_COL_COMMENTS
                    ON ALL_TAB_COLUMNS.COLUMN_NAME = ALL_COL_COMMENTS.COLUMN_NAME

WHERE ALL_TAB_COLUMNS.TABLE_NAME = 'Н_УЧЕНИКИ'
  AND ALL_COL_COMMENTS.TABLE_NAME = 'Н_УЧЕНИКИ';

