CREATE TABLESPACE COOL_GOLD_DISK LOGGING
    DATAFILE '$ORADATA/node02/coolgolddisk01.dbf' SIZE 50 M REUSE,
    '$ORADATA/node03/coolgolddisk02.dbf' SIZE 50 M REUSE,
    '$ORADATA/node02/coolgolddisk03.dbf' SIZE 50 M REUSE
    AUTOEXTEND ON NEXT 1280 K MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE NICE_RED_ROAD LOGGING
    DATAFILE '$ORADATA/node02/loudyellowlab01.dbf' SIZE 50 M REUSE,
    '$ORADATA/node01/loudyellowlab02.dbf' SIZE 50 M REUSE,
    '$ORADATA/node02/loudyellowlab03.dbf' SIZE 50 M REUSE
    AUTOEXTEND ON NEXT 1280 K MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE FAT_YELLOW_IDEA LOGGING
    DATAFILE '$ORADATA/node03/loudbluedata01.dbf' SIZE 50 M REUSE,
    '$ORADATA/node02/loudbluedata02.dbf' SIZE 50 M REUSE
    AUTOEXTEND ON NEXT 1280 K MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;