CREATE DATABASE bestmeat
    USER SYS IDENTIFIED BY admin
    USER SYSTEM IDENTIFIED BY admin
    LOGFILE GROUP 1 ('$ORADATA/bestmeat/redo01.log') SIZE 10 M,
        GROUP 2 ('$ORADATA/bestmeat/redo02.log') SIZE 10 M,
        GROUP 3 ('$ORADATA/bestmeat/redo03.log') SIZE 10 M
    MAXLOGFILES 5
    MAXLOGMEMBERS 5
    MAXLOGHISTORY 1
    MAXDATAFILES 100
    CHARACTER SET AL32UTF8
    NATIONAL CHARACTER SET UTF8
    EXTENT MANAGEMENT LOCAL
    DATAFILE '$ORADATA/node01/uleji76.dbf' SIZE 100 M REUSE,
    '$ORADATA/node04/udizi77.dbf' SIZE 100 M REUSE,
    '$ORADATA/node01/avusi19.dbf' SIZE 100 M REUSE
    SYSAUX DATAFILE '$ORADATA/node04/zej11.dbf' SIZE 300 M REUSE
    DEFAULT TABLESPACE users
    DATAFILE '$ORADATA/node04/ozacara439.dbf' SIZE 300 M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
    DEFAULT TEMPORARY TABLESPACE tempts1
    TEMPFILE '$ORADATA/bestmeat/temp01.dbf'
    SIZE 20 M REUSE AUTOEXTEND ON NEXT 640 K MAXSIZE UNLIMITED
    UNDO TABLESPACE undotbs1
    DATAFILE '$ORADATA/bestmeat/undotbs01.dbf' SIZE 200 M REUSE AUTOEXTEND ON NEXT 5120 K MAXSIZE UNLIMITED;